description: Wait behavior for ZMK

compatible: "zmk,behavior-wait-ms"

include: one_param.yaml

properties:
  wait-ms:
    type: int
    required: true
    description: Time to wait in milliseconds

