# SPDX-License-Identifier: MIT

description: Behavior for Unicode macro input

compatible: "zmk,behavior-macro-unicode"

include: one_param.yaml

properties:
  label:
    type: string
    required: false
    deprecated: true

